name = "gymbear-worker"
main = "worker/src/index.ts"
compatibility_date = "2026-03-20"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "GYMBEAR_KV"
id = "e995f4d85a994d61a9c239deb5f6839b"
preview_id = "8df7241e057249b39230d6357451f221"

[ai]
binding = "AI"
